
import type { LucideIcon } from 'lucide-react';
import {
  Calculator,
  Landmark,
  Globe,
  Bitcoin,
  Currency,
  FileText,
  Building2,
  Image,
  UserCircle,
  Scan,
  Smile,
  ShieldCheck,
  AppWindow,
  Binary,
  GitBranch,
  FileCode,
  ShoppingBag,
  Network,
  KeyRound,
  Regex,
  FileJson,
  Webhook,
  HeartPulse,
  BedDouble,
  Target,
  BadgeDollarSign,
  TrendingDown,
  Briefcase,
  FileSearch,
  Table,
  Link,
  FileDiff,
  GraduationCap,
  FileSpreadsheet,
  Minimize,
} from 'lucide-react';

export type ToolCategory =
  | 'Finance'
  | 'Business'
  | 'Image'
  | 'SEO'
  | 'Developer'
  | 'Health';

export interface Tool {
  name: string;
  slug: string;
  category: ToolCategory;
  description: string;
  longDescription: string;
  icon: string;
  features: string[];
  howItWorks: string[];
  useCases: string[];
}

export const tools: Tool[] = [
  {
    name: 'Plagiarism Checker',
    slug: 'plagiarism-checker',
    category: 'SEO',
    icon: 'FileSearch',
    description: 'ai-contract-summarizer_description',
    longDescription: 'ai-contract-summarizer_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'AI Tutor',
    slug: 'ai-tutor',
    category: 'Business',
    icon: 'GraduationCap',
    description: 'ai-tutor_description',
    longDescription: 'ai-tutor_long_description',
    features: ['ai-tutor_features'],
    howItWorks: ['ai-tutor_how_it_works'],
    useCases: ['ai-tutor_use_cases'],
  },
  {
    name: 'Excel Power Tools',
    slug: 'excel-power-tools',
    category: 'Business',
    icon: 'FileSpreadsheet',
    description: 'excel-power-tools_description',
    longDescription: 'excel-power-tools_long_description',
    features: ['excel-power-tools_features'],
    howItWorks: ['excel-power-tools_how_it_works'],
    useCases: ['excel-power-tools_use_cases'],
  },
  {
    name: 'Image Compressor',
    slug: 'image-compressor',
    category: 'Image',
    icon: 'Minimize',
    description: 'image-compressor_description',
    longDescription: 'image-compressor_long_description',
    features: ['image-compressor_features'],
    howItWorks: ['image-compressor_how_it_works'],
    useCases: ['image-compressor_use_cases'],
  },
  {
    name: 'TinyURL Maker – URL Shortener Tool',
    slug: 'tinyurl-maker',
    category: 'Developer',
    icon: 'Link',
    description: 'tinyurl-maker_description',
    longDescription: 'tinyurl-maker_long_description',
    features: ['tinyurl-maker_features'],
    howItWorks: ['tinyurl-maker_how_it_works'],
    useCases: ['tinyurl-maker_use_cases'],
  },
  {
    name: 'PDF to Word Converter',
    slug: 'pdf-to-word-converter',
    category: 'Business',
    icon: 'FileDiff',
    description: 'pdf-to-word-converter_description',
    longDescription: 'pdf-to-word-converter_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'Global Loan Optimizer',
    slug: 'global-loan-optimizer',
    category: 'Finance',
    icon: 'Globe',
    description: 'global-loan-optimizer_description',
    longDescription: 'global-loan-optimizer_long_description',
    features: ['global-loan-optimizer_features'],
    howItWorks: ['global-loan-optimizer_how_it_works'],
    useCases: ['global-loan-optimizer_use_cases'],
  },
  {
    name: 'Crypto Tax Calculator',
    slug: 'crypto-tax-calculator',
    category: 'Finance',
    icon: 'Bitcoin',
    description: 'crypto-tax-calculator_description',
    longDescription: 'crypto-tax-calculator_long_description',
    features: ['crypto-tax-calculator_features'],
    howItWorks: ['crypto-tax-calculator_how_it_works'],
    useCases: ['crypto-tax-calculator_use_cases'],
  },
  {
    name: 'Forex Arbitrage Checker',
    slug: 'forex-arbitrage-checker',
    category: 'Finance',
    icon: 'Currency',
    description: 'forex-arbitrage-checker_description',
    longDescription: 'forex-arbitrage-checker_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'AI Invoice Generator',
    slug: 'ai-invoice-generator',
    category: 'Business',
    icon: 'FileText',
    description: 'ai-invoice-generator_description',
    longDescription: 'ai-invoice-generator_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'Business Valuation Calculator',
    slug: 'business-valuation-calculator',
    category: 'Business',
    icon: 'Building2',
    description: 'business-valuation-calculator_description',
    longDescription: 'business-valuation-calculator_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'AI Product Background Remover',
    slug: 'ai-product-background-remover',
    category: 'Image',
    icon: 'Image',
    description: 'ai-product-background-remover_description',
    longDescription: 'ai-product-background-remover_long_description',
    features: [],
howItWorks: [],
    useCases: [],
  },
  {
    name: 'AI Headshot Generator',
    slug: 'ai-headshot-generator',
    category: 'Image',
    icon: 'UserCircle',
    description: 'ai-headshot-generator_description',
    longDescription: 'ai-headshot-generator_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'Keyword Cluster Generator',
    slug: 'keyword-cluster-generator',
    category: 'SEO',
    icon: 'AppWindow',
    description: 'keyword-cluster-generator_description',
    longDescription: 'keyword-cluster-generator_long_description',
    features: ['keyword-cluster-generator_features'],
    howItWorks: ['keyword-cluster-generator_how_it_works'],
    useCases: ['keyword-cluster-generator_use_cases'],
  },
  {
    name: 'Content Gap Analyzer',
    slug: 'content-gap-analyzer',
    category: 'SEO',
    icon: 'GitBranch',
    description: 'content-gap-analyzer_description',
    longDescription: 'content-gap-analyzer_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: '1-Click Article Outline Generator',
    slug: '1-click-article-outline-generator',
    category: 'SEO',
    icon: 'FileCode',
    description: '1-click-article-outline-generator_description',
    longDescription: '1-click-article-outline-generator_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'AI Product Description Generator',
    slug: 'ai-product-description-generator',
    category: 'SEO',
    icon: 'ShoppingBag',
    description: 'ai-product-description-generator_description',
    longDescription: 'ai-product-description-generator_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'API Latency Checker',
    slug: 'api-latency-checker',
    category: 'Developer',
    icon: 'Network',
    description: 'api-latency-checker_description',
    longDescription: 'api-latency-checker_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'JWT Decoder & Validator',
    slug: 'jwt-decoder-validator',
    category: 'Developer',
    icon: 'KeyRound',
    description: 'jwt-decoder-validator_description',
    longDescription: 'jwt-decoder-validator_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'AI Regex Generator',
    slug: 'regex-generator-from-text',
    category: 'Developer',
    icon: 'Regex',
    description: 'regex-generator-from-text_description',
    longDescription: 'regex-generator-from-text_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'JSON Hero: Converter & Formatter',
    slug: 'json-excel-converter',
    category: 'Developer',
    icon: 'FileJson',
    description: 'json-excel-converter_description',
    longDescription: 'json-excel-converter_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'Webhook Tester',
    slug: 'webhook-tester',
    category: 'Developer',
    icon: 'Webhook',
    description: 'webhook-tester_description',
    longDescription: 'webhook-tester_long_description',
    features: [],
    howItWorks: [],
    useCases: [],
  },
  {
    name: 'Invoice → Excel Extractor',
    slug: 'invoice-excel-extractor',
    category: 'Business',
    icon: 'Table',
    description: 'invoice-excel-extractor_description',
    longDescription: 'invoice-excel-extractor_long_description',
    features: ['invoice-excel-extractor_features'],
    howItWorks: ['invoice-excel-extractor_how_it_works'],
    useCases: ['invoice-excel-extractor_use_cases'],
  },
];
