
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | All2ools',
  description: 'Read the terms of service for using the All2ools website and its tools.',
};

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-12 md:py-16">
      <div className="mx-auto max-w-3xl prose prose-lg dark:prose-invert">
        <h1 className="text-primary font-headline">Terms of Service</h1>
        <p><em>Last Updated: July 26, 2024</em></p>

        <p>
          Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the All2ools.com website (the "Service") operated by All2ools ("us", "we", or "our").
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using our Service, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          All2ools provides a collection of free online tools. You understand and agree that the Service is provided "AS-IS" and that we assume no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings.
        </p>
        
        <h2>3. No Warranty</h2>
        <p>
          The Service is provided without any warranties of any kind, express or implied. We do not warrant that the tools will be accurate, reliable, or error-free. The results generated by the tools are for informational purposes only and should not be used as a substitute for professional advice. Your use of the Service is at your sole risk.
        </p>

        <h2>4. Limitation of Liability</h2>
        <p>
          In no event shall All2ools, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
        </p>

        <h2>5. Intellectual Property</h2>
        <p>
          The Service and its original content, features, and functionality are and will remain the exclusive property of All2ools and its licensors.
        </p>

        <h2>6. Changes to Terms</h2>
        <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
        </p>

        <h2>7. Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us at: <a href="mailto:terms@all2ools.com" className="text-primary">terms@all2ools.com</a>.
        </p>
      </div>
    </div>
  );
}
